version: "3.8"

services:
  nginx:
    restart: unless-stopped
    image: nginx:1.17.10
    ports:
    - 80:80
    - 443:443
    depends_on:
    - web
    - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email rkrahul8181@gmail.com -d graycode.site --agree-tos
  
  web:
    depends_on:
      - api
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: ./docker/prod/Dockerfile
    hostname: web
    # ports:
    #   - 80:80
    environment:
      - VITE_BACKEND_API_URL=http://localhost
    # this is for docker compose watch mode
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
  api:
    restart: on-failure
    build:
      context: ./backend
      dockerfile: ./docker/prod/Dockerfile
    hostname: api
    # ports:
    #   - 8001:8080

    # docker compose watch mode for development
    develop:
      watch:
        - path: ./backend
          action: rebuild
        - path: ./backend
          action: rebuild
        - path: ./backend
          target: /app
          action: sync



